interest.rate.savings=0.0125
system.account=NBBANK0000
mailtrap.host=sandbox.smtp.mailtrap.io
mailtrap.port=2525
mailtrap.username=475eb79406a2af
mailtrap.password=645ac872d7f4fd
app.email=info@nationalbank.net